# These are Dockerfiles specifically made
# to get our projects set up in a development environment

FROM node:14.14.0-alpine
WORKDIR "/app"
COPY package.json .
RUN npm install
COPY . .
CMD ["npm","run","dev"]